import React, { useState, useRef } from 'react';
import { 
  Upload, 
  FileText, 
  CheckCircle2, 
  AlertCircle, 
  Play, 
  Save, 
  Trash2, 
  Code2, 
  Sparkles,
  ArrowRight
} from 'lucide-react';
import { validateAndNormalizeExam } from '../utils/validator';
import { SAMPLE_EXAM_JSON } from '../data/jsonSchema';

export function ExamUploader({ onExamReady, onSavedExam }) {
  const [jsonText, setJsonText] = useState('');
  const [validationResult, setValidationResult] = useState(null);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef(null);

  const handleValidate = (raw) => {
    const textToTest = raw !== undefined ? raw : jsonText;
    if (!textToTest.trim()) {
      setValidationResult(null);
      return;
    }
    const result = validateAndNormalizeExam(textToTest);
    setValidationResult(result);
  };

  const handleTextChange = (e) => {
    const val = e.target.value;
    setJsonText(val);
    if (val.trim()) {
      handleValidate(val);
    } else {
      setValidationResult(null);
    }
  };

  const handleFileDrop = (e) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const processFile = (file) => {
    if (!file.name.endsWith('.json') && file.type !== 'application/json') {
      setValidationResult({
        valid: false,
        error: 'Please upload a valid .json file.',
        data: null
      });
      return;
    }
    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target.result;
      setJsonText(content);
      handleValidate(content);
    };
    reader.readAsText(file);
  };

  const handleLoadSample = () => {
    const sampleStr = JSON.stringify(SAMPLE_EXAM_JSON, null, 2);
    setJsonText(sampleStr);
    handleValidate(sampleStr);
  };

  const handleStartExam = () => {
    if (validationResult && validationResult.valid && validationResult.data) {
      if (onSavedExam) onSavedExam(validationResult.data);
      if (onExamReady) onExamReady(validationResult.data);
    }
  };

  const handleFormatJson = () => {
    try {
      const obj = JSON.parse(jsonText);
      setJsonText(JSON.stringify(obj, null, 2));
    } catch (e) {
      // ignore if invalid
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-xs border border-[#d1d7dc] p-6 sm:p-8">
      <div className="mb-6">
        <h2 className="text-xl sm:text-2xl font-extrabold text-[#2d2f31] flex items-center space-x-2">
          <Upload className="w-6 h-6 text-[#a435f0]" />
          <span>Upload & Practice Your Exam</span>
        </h2>
        <p className="text-xs sm:text-sm text-[#6a6f73] mt-1">
          Paste the JSON generated by your AI (ChatGPT, Claude, Gemini, DeepSeek) or drag and drop a .json file.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column: Drag & Drop and File Picker */}
        <div className="space-y-4">
          <div
            onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={handleFileDrop}
            onClick={() => fileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-all flex flex-col items-center justify-center min-h-[220px] ${
              isDragging
                ? 'border-[#a435f0] bg-[#f5eefc]'
                : 'border-[#d1d7dc] hover:border-[#a435f0] hover:bg-gray-50'
            }`}
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileSelect}
              accept=".json,application/json"
              className="hidden"
            />
            <div className="w-12 h-12 rounded-full bg-[#f5eefc] text-[#a435f0] flex items-center justify-center mb-3">
              <Upload className="w-6 h-6" />
            </div>
            <p className="text-sm font-bold text-[#2d2f31]">
              Click to browse or drag & drop .json file here
            </p>
            <p className="text-xs text-[#6a6f73] mt-1">
              Supports standard UdemyMock JSON format
            </p>
          </div>

          <div className="flex items-center justify-between text-xs">
            <span className="text-[#6a6f73]">Need an instant sample to test?</span>
            <button
              type="button"
              onClick={handleLoadSample}
              className="text-[#a435f0] hover:underline font-bold flex items-center space-x-1"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>Load Sample JSON</span>
            </button>
          </div>
        </div>

        {/* Right Column: Paste Raw JSON */}
        <div className="space-y-3 flex flex-col">
          <div className="flex items-center justify-between text-xs font-semibold text-[#2d2f31]">
            <span className="flex items-center space-x-1.5">
              <Code2 className="w-4 h-4 text-[#a435f0]" />
              <span>Or Paste JSON Directly:</span>
            </span>
            {jsonText && (
              <div className="space-x-2">
                <button
                  type="button"
                  onClick={handleFormatJson}
                  className="text-gray-600 hover:text-[#a435f0]"
                >
                  Beautify JSON
                </button>
                <button
                  type="button"
                  onClick={() => { setJsonText(''); setValidationResult(null); }}
                  className="text-red-600 hover:underline"
                >
                  Clear
                </button>
              </div>
            )}
          </div>

          <textarea
            rows={8}
            value={jsonText}
            onChange={handleTextChange}
            placeholder={`{\n  "title": "AWS SAA-C03 Mock Exam",\n  "durationMinutes": 60,\n  "questions": [\n    {\n      "id": 1,\n      "question": "Which service...",\n      "options": ["A", "B", "C", "D"],\n      "correctAnswer": 0,\n      "explanation": "..."\n    }\n  ]\n}`}
            className="w-full h-44 px-3 py-2 border border-[#d1d7dc] rounded-lg font-mono text-xs focus:outline-none focus:border-[#a435f0] text-gray-800 bg-[#fbfbfb]"
          />
        </div>
      </div>

      {/* Validation Feedback Banner */}
      {validationResult && (
        <div className="mt-6">
          {validationResult.valid ? (
            <div className="bg-[#f2faf3] border border-emerald-300 rounded-xl p-5">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div className="flex items-start space-x-3">
                  <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-0.5" />
                  <div>
                    <h4 className="font-bold text-emerald-900 text-sm sm:text-base">
                      Exam Ready: {validationResult.data.title}
                    </h4>
                    <p className="text-xs text-emerald-700 mt-1">
                      {validationResult.data.questions.length} questions detected • {validationResult.data.durationMinutes} mins duration • Passing score: {validationResult.data.passingScore}%
                    </p>
                    {validationResult.data.domains && validationResult.data.domains.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {validationResult.data.domains.slice(0, 4).map((dom, dIdx) => (
                          <span key={dIdx} className="bg-emerald-100 text-emerald-800 text-[10px] font-semibold px-2 py-0.5 rounded">
                            {dom}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                <div className="flex items-center space-x-2 shrink-0">
                  <button
                    type="button"
                    onClick={handleStartExam}
                    className="w-full sm:w-auto px-5 py-2.5 rounded-lg font-bold text-sm bg-[#a435f0] hover:bg-[#8710d8] text-white shadow-sm flex items-center justify-center space-x-2 transition-all hover:scale-[1.02]"
                  >
                    <span>Start Practice Test</span>
                    <ArrowRight className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {validationResult.warnings && validationResult.warnings.length > 0 && (
                <div className="mt-3 pt-3 border-t border-emerald-200 text-xs text-emerald-800">
                  <span className="font-semibold">Note:</span> {validationResult.warnings.join(' ')}
                </div>
              )}
            </div>
          ) : (
            <div className="bg-[#fdf3f2] border border-red-300 rounded-xl p-4 flex items-start space-x-3 text-red-900 text-xs sm:text-sm">
              <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Validation Issue in JSON:</p>
                <p className="mt-0.5 text-red-700 font-mono text-xs">{validationResult.error}</p>
                <p className="mt-2 text-xs text-red-600">
                  Tip: Make sure you didn't leave trailing commas and that 'questions', 'options', 'correctAnswer', and 'explanation' fields are populated.
                </p>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
